name:                ann-accelerate
version:             0.1.0.0
github:              "noahmartinwilliams/ann-accelerate"
license:             BSD3
author:              "Noah Martin Williams"
maintainer:          "noahmartinwilliams@gmail.com"
copyright:           "2023 Noah Martin Williams"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ann-accelerate#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  ghc-options:
  - -threaded
  - -rtsopts
  dependencies:
  - accelerate
  - cereal
  - normaldistribution
  - random
  - bytestring
  - accelerate-io
  - accelerate-io-bytestring
  - bytestring-conversion

executables:
  mnist:
    main:                Main.hs
    source-dirs:         mnist
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ann-accelerate
    - accelerate
    - base
    - split
    - bytestring
    - accelerate-llvm-ptx
    - random
    - parallel

  mnistTest:
    main:                Main.hs
    source-dirs:         mnistTest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ann-accelerate
    - accelerate
    - base
    - split
    - bytestring
    - accelerate-llvm-ptx
    - random

  mkNet:
    main:                Main.hs
    source-dirs:         mkNet
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ann-accelerate
    - accelerate
    - base
    - split
    - bytestring
    - random

  calcNet:
    main:                Main.hs
    source-dirs:         calcNet
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ann-accelerate
    - accelerate
    - base
    - split
    - bytestring
    - accelerate-llvm-ptx

  trainNet:
    main:                Main.hs
    source-dirs:         trainNet
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - accelerate
    - base
    - random
    - parallel
    - accelerate-llvm-ptx
    - ann-accelerate
    - split
    - bytestring

  genOrGate:
    main:                Main.hs
    source-dirs:         genOrGate
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - accelerate
    - base
    - random
    - parallel

tests:
  ann-accelerate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ann-accelerate
